echo 'STEP 1:'
echo 'adduser <username>'
echo 'STEP 2:'
echo 'enter a password'
echo 'STEP 3:'
echo 'run the set-exp script'
echo 'OPTIONAL STEP:'
echo 'if in the future you need to extend the account expiration: run the ext-exp script'
echo 'STEP 4:'
echo 'run the rsync-ssh script'
