echo 'STEP 1:'
echo -e 'adduser <username>\n'
echo 'STEP 2:'
echo -e 'enter a password\n'
echo 'STEP 3:'
echo -e 'run the set-exp script\n'
echo 'OPTIONAL STEP:'
echo -e 'if in the future you need to extend the account expiration: run the ext-exp script\n'
echo 'STEP 4:'
echo -e 'run the rsync-ssh script\n'
echo 'all scripts are located in /home/byte/bin'
